# Generated by Django 5.2.1 on 2025-05-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calorías por 100g (kcal)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fibra (g)', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='Desconocido', help_text='Origen', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='potassium',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Potasio (mg)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_c',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vitamina C (mg)', max_digits=5),
        ),
    ]
