# Generated by Django 5.2.1 on 2025-05-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default='Nuevo', max_length=50),
        ),
    ]
