# Generated by Django 5.2.1 on 2025-05-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
    ]
